name: time_pad
description: "Time Pad"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # for design_system
  cupertino_icons: ^1.0.6
  l: ^4.0.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.13.1
  rename_app: ^1.6.1

  # for locale storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3

  # for state management
  flutter_riverpod: ^2.4.10

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # for Network
  dio: ^5.4.1
  connectivity_plus: ^6.0.3

  # for navigation
  go_router: ^14.1.1

  # meta
  package_info_plus: ^8.0.0
  meta: ^1.9.0

  # generator
#  flutter_gen: any

  image_picker: ^1.1.2
  image_picker_web: ^4.0.0
  qr_code_scanner: ^1.0.1
  camera: ^0.11.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
#  flutter_gen_runner: ^5.6.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
#    - assets/images/
  #   - assets/icons/
  #   - assets/fonts/

# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/unicorn_logo.png"

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/common/l10n
  template-arb-file: intl_en.arb
  output-localization-file: app_localizations.dart
  use_deferred_loading: false